### ISSUE TITLE
Angular 13

### ISSUE THREAD

**Issue by doczoidberg** [briebug/mat-dialog-schematic#1]
Hi,

I tried your useful schematics but get an error:

 ng g @briebug/mat-dialog-schematic:mat-dialog
```

An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "...\angular-errors.log" for further details.
```

**Comment by anthonymjones** [comment]
Hi @doczoidberg! This repository is no longer actively maintained and hasn't been updated since Angular version 7. If you're interested in working on an update/fix for this issue, I'd be happy to review a PR.
